---
title: "Corridor_Validation"
author: "Robert Saldivar"
date: "January 14, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(RColorBrewer)
library(here)
library(janitor)
library(kableExtra)

Random_Focal_Species <- read_csv("Random_Focal_Species_Extract.csv")
Random_Fisher <- read_csv("Random_Fisher_Extract.csv")
Random_Bobcat <- read_csv("Random_Bobcat_Extract.csv")
Random_Bear <- read_csv("Random_Bear_Extract.csv")
Bear <- read_csv("Bear_Extract.csv")
Bobcat <- read_csv("Bobcat_Extract.csv")
Fisher <- read_csv("Fisher_Extract.csv")
Focal_Species <- read_csv("Focal_Species_Extract.csv")
```

```{r}
#looking at the summary information for bears 

bear_summary <- Bear %>%
  group_by(verbatimScientificName) %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for random bears points

random_bear_summary <- Random_Bear %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for bobcats points

bobcat_summary <- Bobcat %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for random bobcat points

random_bobcat_summary <- Random_Bobcat %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for Fisher points

fisher_summary <- Fisher %>%
  group_by(verbatimScientificName) %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for random fisher points

random_fisher_summary <- Random_Fisher %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )
```

```{r}
#looking at the summary information for all focal species points

Focal_Species_summary <- Focal_Species %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )

```

```{r}
#looking at the summary information for random focal species points

random_focal_species_summary <- Random_Focal_Species %>%
  summarize( 
    resist_mean = mean(Nat_resistance_2011),
    resist_sd = sd(Nat_resistance_2011),
    resist_length = length(Nat_resistance_2011),
    core2_mean = mean(Nat_2c_default_corridors),
    core2_sd = sd(Nat_2c_default_corridors),
    core3_mean = mean(Nat_3c_default_corridors),
    core3_sd = sd(Nat_3c_default_corridors),
    bar_mean = mean(GP_Nat_bar_corridors),
    bar_sd = sd(GP_Nat_bar_corridors),
    node_mean = mean(GP_Nat_node_corridors),
    node_sd = sd(GP_Nat_node_corridors),
    node_close_mean = mean(node_close_corridors),
    node_close_sd = sd(node_close_corridors),
    bar_close_mean = mean(GP_bar_close_corridors),
    bar_close_sd = sd(GP_bar_close_corridors),
    core2_trunk_mean = mean(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core2_trunk_sd = sd(Nat_2c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_mean = mean(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    core3_trunk_sd = sd(Nat_3c_default_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_mean = mean(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    bar_trunk_sd = sd(GP_Nat_bar_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_mean = mean(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_trunk_sd = sd(GP_Nat_node_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_mean = mean(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    node_close_trunk_sd = sd(node_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_mean = mean(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE),
    bar_close_trunk_sd = sd(GP_bar_close_corridors_truncated_at_200k, na.rm = TRUE)
  )
```

```{r}
#Going to try to join the summary tables into a together

bear_table <- full_join(bear_summary, random_bear_summary)
bobcat_table <- full_join(bobcat_summary, random_bobcat_summary)
fisher_table <- full_join(fisher_summary, random_fisher_summary)
focal_species_table <- full_join(Focal_Species_summary, random_focal_species_summary)


```


```{r}
#Running Statistical Tests for bears againgsd the various identified corridors

bear_ttest_resistance <- t.test(Bear$Nat_resistance_2011, Random_Bear$Nat_resistance_2011)
bear_ttest_2core <- t.test(Bear$Nat_2c_default_corridors, Random_Bear$Nat_2c_default_corridors)
bear_ttest_3core <- t.test(Bear$Nat_3c_default_corridors, Random_Bear$Nat_3c_default_corridors)
bear_ttest_bar <- t.test(Bear$GP_Nat_bar_corridors, Random_Bear$GP_Nat_bar_corridors)
bear_ttest_bar_close <- t.test(Bear$GP_bar_close_corridors, Random_Bear$GP_bar_close_corridors)
bear_ttest_node <- t.test(Bear$GP_Nat_node_corridors, Random_Bear$GP_Nat_node_corridors)
bear_ttest_node_close <- t.test(Bear$node_close_corridors, Random_Bear$node_close_corridors)
bear_ttest_2core_trunk <- t.test(Bear$Nat_2c_default_corridors_truncated_at_200k, Random_Bear$Nat_2c_default_corridors_truncated_at_200k, conf.level = 0.95)
bear_ttest_3core_trunk <- t.test(Bear$Nat_3c_default_corridors_truncated_at_200k, Random_Bear$Nat_3c_default_corridors_truncated_at_200k)
bear_ttest_bar_trunk <- t.test(Bear$GP_Nat_bar_corridors_truncated_at_200k, Random_Bear$GP_Nat_bar_corridors_truncated_at_200k)
bear_ttest_bar_close_trunk <- t.test(Bear$GP_bar_close_corridors_truncated_at_200k, Random_Bear$GP_bar_close_corridors_truncated_at_200k)
bear_ttest_node_trunk <- t.test(Bear$GP_Nat_node_corridors_truncated_at_200k, Random_Bear$GP_Nat_node_corridors_truncated_at_200k)
bear_ttest_node_close_trunk <- t.test(Bear$node_close_corridors_truncated_at_200k, Random_Bear$node_close_corridors_truncated_at_200k)

bear_ttest_resistance
bear_ttest_2core
bear_ttest_3core
bear_ttest_bar
bear_ttest_bar_close
bear_ttest_node
bear_ttest_node_close
bear_ttest_2core_trunk
bear_ttest_3core_trunk
bear_ttest_bar_trunk
bear_ttest_bar_close_trunk
bear_ttest_node_trunk
bear_ttest_node_close_trunk

#There is a significant difference for all of the corridors between the between the corridors between bear observations and random bear points, except for the nodes corridor. 


```

```{r}
#Running Statistical Tests for bobcats againgsd the various identified corridors

bobcat_ttest_resistance <- t.test(Bobcat$Nat_resistance_2011, Random_Bobcat$Nat_resistance_2011)
bobcat_ttest_2core <- t.test(Bobcat$Nat_2c_default_corridors, Random_Bobcat$Nat_2c_default_corridors)
bobcat_ttest_3core <- t.test(Bobcat$Nat_3c_default_corridors, Random_Bobcat$Nat_3c_default_corridors)
bobcat_ttest_bar <- t.test(Bobcat$GP_Nat_bar_corridors, Random_Bobcat$GP_Nat_bar_corridors)
bobcat_ttest_bar_close <- t.test(Bobcat$GP_bar_close_corridors, Random_Bobcat$GP_bar_close_corridors)
bobcat_ttest_node <- t.test(Bobcat$GP_Nat_node_corridors, Random_Bobcat$GP_Nat_node_corridors)
bobcat_ttest_node_close <- t.test(Bobcat$node_close_corridors, Random_Bobcat$node_close_corridors)
bobcat_ttest_2core_trunk <- t.test(Bobcat$Nat_2c_default_corridors_truncated_at_200k, Random_Bobcat$Nat_2c_default_corridors_truncated_at_200k)
bobcat_ttest_3core_trunk <- t.test(Bobcat$Nat_3c_default_corridors_truncated_at_200k, Random_Bobcat$Nat_3c_default_corridors_truncated_at_200k)
bobcat_ttest_bar_trunk <- t.test(Bobcat$GP_Nat_bar_corridors_truncated_at_200k, Random_Bobcat$GP_Nat_bar_corridors_truncated_at_200k)
bobcat_ttest_bar_close_trunk <- t.test(Bobcat$GP_bar_close_corridors_truncated_at_200k, Random_Bobcat$GP_bar_close_corridors_truncated_at_200k)
bobcat_ttest_node_trunk <- t.test(Bobcat$GP_Nat_node_corridors_truncated_at_200k, Random_Bobcat$GP_Nat_node_corridors_truncated_at_200k)
bobcat_ttest_node_close_trunk <- t.test(Bobcat$node_close_corridors_truncated_at_200k, Random_Bobcat$node_close_corridors_truncated_at_200k)

bobcat_ttest_resistance
bobcat_ttest_2core
bobcat_ttest_3core
bobcat_ttest_bar
bobcat_ttest_bar_close
bobcat_ttest_node
bobcat_ttest_node_close
bobcat_ttest_2core_trunk
bobcat_ttest_3core_trunk
bobcat_ttest_bar_trunk
bobcat_ttest_bar_close_trunk
bobcat_ttest_node_trunk
bobcat_ttest_node_close_trunk

#There is a significant difference for all of the corridors between the between the corridors between bobcat observations and random bobcat points.

```

```{r}
#Running Statistical Tests for fishers againgsd the various identified corridors

fisher_ttest_resistance <- t.test(Fisher$Nat_resistance_2011, Random_Fisher$Nat_resistance_2011)
fisher_ttest_2core <- t.test(Fisher$Nat_2c_default_corridors, Random_Fisher$Nat_2c_default_corridors)
fisher_ttest_3core <- t.test(Fisher$Nat_3c_default_corridors, Random_Fisher$Nat_3c_default_corridors)
fisher_ttest_bar <- t.test(Fisher$GP_Nat_bar_corridors, Random_Fisher$GP_Nat_bar_corridors)
fisher_ttest_bar_close <- t.test(Fisher$GP_bar_close_corridors, Random_Fisher$GP_Nat_bar_corridors)
fisher_ttest_node <- t.test(Fisher$GP_Nat_node_corridors, Random_Fisher$GP_Nat_node_corridors)
fisher_ttest_node_close <- t.test(Fisher$node_close_corridors, Random_Fisher$node_close_corridors)
fisher_ttest_2core_trunk <- t.test(Fisher$Nat_2c_default_corridors_truncated_at_200k, Random_Fisher$Nat_2c_default_corridors_truncated_at_200k)
fisher_ttest_3core_trunk <- t.test(Fisher$Nat_3c_default_corridors_truncated_at_200k, Random_Fisher$Nat_3c_default_corridors_truncated_at_200k)
fisher_ttest_bar_trunk <- t.test(Fisher$GP_Nat_bar_corridors_truncated_at_200k, Random_Fisher$GP_Nat_bar_corridors_truncated_at_200k)
fisher_ttest_bar_close_trunk <- t.test(Fisher$GP_bar_close_corridors_truncated_at_200k, Random_Fisher$GP_bar_close_corridors_truncated_at_200k)
fisher_ttest_node_trunk <- t.test(Fisher$GP_Nat_node_corridors_truncated_at_200k, Random_Fisher$GP_Nat_node_corridors_truncated_at_200k)
fisher_ttest_node_close_trunk <- t.test(Fisher$node_close_corridors_truncated_at_200k, Random_Fisher$node_close_corridors_truncated_at_200k)

fisher_ttest_resistance
fisher_ttest_2core
fisher_ttest_3core
fisher_ttest_bar
fisher_ttest_bar_close
fisher_ttest_node
fisher_ttest_node_close
fisher_ttest_2core_trunk
fisher_ttest_3core_trunk
fisher_ttest_bar_trunk
fisher_ttest_bar_close_trunk
fisher_ttest_node_trunk
fisher_ttest_node_close_trunk
```

```{r}
#Running Statistical Tests for all focal species againgsd the various identified corridors

focal_species_ttest_resistance <- t.test(Focal_Species$Nat_resistance_2011, Random_Focal_Species$Nat_resistance_2011)
focal_species_ttest_2core <- t.test(Focal_Species$Nat_2c_default_corridors, Random_Focal_Species$Nat_2c_default_corridors)
focal_species_ttest_3core <- t.test(Focal_Species$Nat_3c_default_corridors, Random_Focal_Species$Nat_3c_default_corridors)
focal_species_ttest_bar <- t.test(Focal_Species$GP_Nat_bar_corridors, Random_Focal_Species$GP_Nat_bar_corridors)
focal_species_ttest_bar_close <- t.test(Focal_Species$GP_bar_close_corridors, Random_Focal_Species$GP_bar_close_corridors)
focal_species_ttest_node <- t.test(Focal_Species$GP_Nat_node_corridors, Random_Focal_Species$GP_Nat_node_corridors)
focal_species_ttest_node_close <- t.test(Focal_Species$node_close_corridors, Random_Focal_Species$node_close_corridors)
focal_species_ttest_2core_trunk <- t.test(Focal_Species$Nat_2c_default_corridors_truncated_at_200k, Random_Fisher$Nat_2c_default_corridors_truncated_at_200k)
focal_species_ttest_3core_trunk <- t.test(Focal_Species$Nat_3c_default_corridors_truncated_at_200k, Random_Focal_Species$Nat_3c_default_corridors_truncated_at_200k)
focal_species_ttest_bar_trunk <- t.test(Focal_Species$GP_Nat_bar_corridors_truncated_at_200k, Random_Focal_Species$GP_Nat_bar_corridors_truncated_at_200k)
focal_species_ttest_bar_close_trunk <- t.test(Focal_Species$GP_bar_close_corridors_truncated_at_200k, Random_Focal_Species$GP_bar_close_corridors_truncated_at_200k)
focal_species_ttest_node_trunk <- t.test(Focal_Species$GP_Nat_node_corridors_truncated_at_200k, Random_Focal_Species$GP_Nat_node_corridors_truncated_at_200k)
focal_species_ttest_node_close_trunk <- t.test(Focal_Species$node_close_corridors_truncated_at_200k, Random_Focal_Species$node_close_corridors_truncated_at_200k)

focal_species_ttest_resistance
focal_species_ttest_2core
focal_species_ttest_3core
focal_species_ttest_bar
focal_species_ttest_bar_close
focal_species_ttest_node
focal_species_ttest_node_close
focal_species_ttest_2core_trunk
focal_species_ttest_3core_trunk
focal_species_ttest_bar_trunk
focal_species_ttest_bar_close_trunk
focal_species_ttest_node_trunk
focal_species_ttest_node_close_trunk

```

